# Pydantic models for request and response bodies

from datetime import datetime
from typing import Optional  
from pydantic import BaseModel
# datetime → used for timestamps
# Optional[str] → indicates a field can be str or None
# BaseModel → all Pydantic models must inherit from this


class WordBase(BaseModel):
    term: str
    meaning: str
    example: Optional[str] = None 
    part_of_speech: Optional[str] = None
# WordBase is not used directly for API endpoints but is inherited by the others.
# 	•	term (str) → required
# 	•	meaning (str) → required
# 	•	example (str | None) → optional sentence


class WordCreate(WordBase):
    pass
# This model inherits everything from WordBase

class WordRead(WordBase):
    id: int
    created_at: datetime

    class Config:
        orm_mode = True
# Additional fields from the database:
# 	•	id (int) → auto-generated by the DB
# 	•	created_at (datetime) → generated at insert time

# Config.orm_mode = True
# This allows Pydantic to accept SQLAlchemy ORM objects and convert them to JSON.
# Without this, returning a SQLAlchemy model would fail.
