"""create words table

Revision ID: 0582100dc291
Revises: 
Create Date: 2025-12-18 13:56:37.825668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0582100dc291'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_index(op.f('ix_words_term'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('term', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meaning', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('example', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('words_pkey'))
    )
    op.create_index(op.f('ix_words_term'), 'words', ['term'], unique=False)
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    # ### end Alembic commands ###
