"""add part_of_speech to words

Revision ID: c089da0f07d4
Revises: e200a57e58f4
Create Date: 2025-12-18 14:28:29.604613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c089da0f07d4'
down_revision: Union[str, Sequence[str], None] = 'e200a57e58f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('part_of_speech', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'part_of_speech')
    # ### end Alembic commands ###
